backend:
  name: github
  repo: LalitMaganti/lalitm.com-source
  branch: main
  base_url: https://lalitm.com
  auth_endpoint: /api/auth

# For local development, uncomment this and comment out github above
# backend:
#   name: test-repo

# Editorial workflow: drafts as pull requests
# publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img"

# Load site styles in CMS preview
editor:
  preview: true

collections:
  - name: "post"
    label: "Blog Posts"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ"}
      - {label: "Author", name: "author", widget: "string", default: "Lalit Maganti"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "page"
    label: "Pages"
    folder: "content/page"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ"}
      - {label: "Author", name: "author", widget: "string", default: "Lalit Maganti"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true, required: false}
      - {label: "Body", name: "body", widget: "markdown"}
